# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/purchasedecision
spring.datasource.username=vaishnavi
spring.datasource.password=password123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Spring Security for now (we'll configure it properly later)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# App
server.port=8080

jwt.secret=3b76f6668251f8fb63a4accf13fd4b52d6ae5b4a1d0ab3a29d3b7085bc153cf7
jwt.expiration=86400000